### PR TITLE
Add new has_multiple_winning_apartments field for reservations - ASU-1443

### PR DESCRIPTION
**Pull request by juhakujala**

### CODE REVIEW

**Review by tuomas777 — COMMENTED** [review]
This is more of a design question, but I wonder whether we want to show the bell icon for cancelled reservations, probably not? At least not the normal red one I guess.

**Comment by juhakujala** [comment]
> This is more of a design question, but I wonder whether we want to show the bell icon for cancelled reservations, probably not? At least not the normal red one I guess.

Does this actually ever happen? If I understood the backend part right, `has_multiple_winning_apartments` should be false for cancelled reservations.

https://github.com/City-of-Helsinki/apartment-application-service/blob/develop/application_form/api/sales/serializers.py#L78-L95

**Comment by tuomas777** [comment]
> > This is more of a design question, but I wonder whether we want to show the bell icon for cancelled reservations, probably not? At least not the normal red one I guess.
> 
> Does this actually ever happen? If I understood the backend part right, `has_multiple_winning_apartments` should be false for cancelled reservations.
> 
> https://github.com/City-of-Helsinki/apartment-application-service/blob/develop/application_form/api/sales/serializers.py#L78-L95

I don't think there is anything that prevents cancelled reservations from having true.

**Comment by juhakujala** [comment]
Let's always hide the icon from canceled reservations then. I'll make a change for this.

**Review by tuomas777 — APPROVED** [review]
🔔

**Pull request merged**
